targets:
  $default:
    builders:
      slang_build_runner:
        options:
          base_locale: en
          input_directory: lib/i18n
          input_file_pattern: .json
          output_directory: lib/generated
          fallback_strategy: base_locale
          flutterIntegration: true
       